# This workflow will build and publish the final artifact
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Finalization

on:
  push:
    branches:
      - main

jobs:
  release:
    env:
      CLONE_URL: ${{ github.event.pull_request.base.repo.clone_url }}
      BRANCH_NAME: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      #      - name: "Check Master Misalignment"
      #        run: |
      #          # get master commit id
      #          masterCommitId=$(git log -n1 --format="%h")
      #          echo $masterCommitId
      #          # get pr commit it
      #          echo "Check misalignment"
      - name: "Derive and set version"
        run: |
          git fetch --tag
          lastTag=$( git tag -l | tail -1 )
          echo $lastTag
          IFS='.' read -r X Y Z <<< "$lastTag"
          X="${X//v/}"    # tag version to pom version
          ((Z++)) || {
            echo "UNABLE TO DETERMINE THE POM VERSION" 1>&2
            exit 99
          }
          mvn versions:set -DnewVersion="$X.$Y.$Z"
          echo "Version updated"
          mvn clean package > mvn-output.log
#      - name: "Build final artifact"
#        run: |
#          echo "Build final artifact"
#      - name: "Publish final artifact"
#        run: |
#          echo "Publish final artifact"
