# This workflow will build and publish the final artifact
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Finalization

on:
  push:
    branches:
      - main

jobs:
  release:
    env:
      CLONE_URL: ${{ github.event.pull_request.base.repo.clone_url }}
      BRANCH_NAME: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout"
        uses: actions/checkout@v2
#      - name: "Check Master Misalignment"
#        run: |
#          # get master commit id
#          masterCommitId=$(git log -n1 --format="%h")
#          echo $masterCommitId
#          # get pr commit it
#          echo "Check misalignment"
      - name: "Derive and set version"
        run: |
          git fetch --tag
          lastTag=$( git tag -l | tail -1 )
          echo "######## 1"
          echo $lastTag
          IFS='.' read -r X Y Z <<< "$lastTag"
          echo "######## 2"
          echo "$X -- $Y -- $Z"
          ((Z++)) || true
          echo "######## 3"
          echo "$Z"
          mvn versions:set -DnewVersion="$X.$Y.$Z"
          echo "######## 4"
          mvn clean verify
          echo "Version updated"
#      - name: "Build final artifact"
#        run: |
#          echo "Build final artifact"
#      - name: "Publish final artifact"
#        run: |
#          echo "Publish final artifact"
