# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        test-type: ['fast-test', 'fast-test,slow-test']
        include:
          # includes the value of the rebase variable depending on the test type of the matrix
          # includes the dependency between the 2 generated jobs to ensure sequential runs
          - test-type: 'fast-test'
            rebase: false
            needs: ''
          - test-type: 'fast-test,slow-test'
            rebase: true
            needs: 'fast-test'
#    needs: ${{ matrix.needs }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.1
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Rebase
        if: ${{ matrix.rebase }}
        run: |
          # rebase on main branch
          git fetch
          git checkout -b main origin/main
          git rebase main || git rebase --abort
      - name: Run tests with Maven
        run: mvn -B test -Dgroups=${{ matrix.test-type }}
