# This workflow will merge a pull request in the target branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Merge

on:
#  # Try merging pull requests belonging to a workflow run.
#  workflow_run:
#    workflows:
#      - CI
#    types:
#      - completed

  # Try merging a pull request when it is approved.
  pull_request_review:
    types:
      - submitted

  # Try merging a pull request when a label is added
  pull_request:
    types: [ labeled ]

jobs:

  merge:
    if: github.event.review.state == 'approved' || ( ! github.event.review && github.event.label.name == 'approved' )
    runs-on: ubuntu-latest
    steps:
#      - name: "Logs"
#        uses: hmarr/debug-action@v1.0.0

      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Check if rebase is required"
        run: |
          echo "CURRENT BRANCH ${currBranch}"
          hash1=$(git show-ref --heads -s main)
          hash2=$(git merge-base main "${GITHUB_HEAD_REF}")
          [ "${hash1}" = "${hash2}" ] && echo "OK" || echo "Rebase is required"
          [ "${hash1}" = "${hash2}" ] && exit 0 || exit 1
      - name: "Merge"
        uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.MERGE_PAL_TOKEN }}
#          merge-method: merge
          do-not-merge-labels: never-merge
#          required-labels: automerge
#          pull-request: ${{ github.event.inputs.pull-request }}
#          dry-run: true
