name: Release

on:
  release:
    types:
      - created

jobs:
  dosomething:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: DOnE
        run: echo "DOOOOOOOOOONE"
