# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_run:
    workflows: [ "Preparation" ]
    types:
      - completed

jobs:
  owasp:
    runs-on: ubuntu-latest
    steps:
      - name: "OWASP checks"
        run: echo 'OWASP CHECKS PASSED'
