# This workflow will prepare every thing required to proceed with a PR
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Preparation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}
#      - uses: nelonoel/branch-name@v1.0.1
          # Use branch name for whatever purpose
#      - run: echo ${BRANCH_NAME}
      - name: Checkout
        run: |
          ls -la
          pwd
          git status
          git clone ${github.pull_request.head.repo.clone_url} repo_folder
          cd repo_folder
          echo "in repo folder"
          pwd
          ls -la
          git checkout -b ${github.pull_request.head.ref}
      - name: "Guard file update"
        run: |
          git config --global user.email "cicd@entando.com"
          git config --global user.name "firegloves"
          hash=$(sha256sum<<<"${GITHUB_REF}")
          echo "$hash" > guard
          # ---- add existence check
          git add guard
          git commit guard -m 'guard file update'
          # git push
          echo "branch ${BRANCH_NAME}"
          git push origin HEAD:${BRANCH_NAME}
          echo 'Guard file updated'
      - name: "BOM update"
        run: echo 'BOM updated'
