name: Publish to Entando Nexus

on:
  #  push:
  #    branches:
  #      - "rel_v*"
  #    tags:
  #      - 'v*'
  release:
    types:
      #      - published
      #      - unpublished
      - created
#      - edited
#      - deleted
#      - prereleased
#      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Entando Nexus Repository"
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ng-pipelines
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: "Publish package"
        run: |
          mvn --batch-mode deploy -X
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      - name: "Update entando-core-bom"
        env:
          ENTANDO_CORE_BOM_FOLDER: "entando-core-bom"
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "##### TAG NAME $TAG_NAME"

          tagValue=$(echo "$TAG_NAME" | sed 's/^v\(.*\)/\1/')
          echo "##### TAG VALUE $tagValue"

          # install xmlstarlet
          sudo apt-get install xmlstarlet &> /dev/null
          echo "xmlstarlet installed"

          # get the current artifact version in the entando-core-bom pom.xml file
          artifactId=$(xmlstarlet sel -N pom="http://maven.apache.org/POM/4.0.0" -t \
            -m "/pom:project" \
            -v "./pom:artifactId" pom.xml)

          echo "##### ARTIFACT ID $artifactId"

          # clone entando-core-bom
          mkdir "$ENTANDO_CORE_BOM_FOLDER" && cd "$ENTANDO_CORE_BOM_FOLDER"
          git clone https://github.com/entando-ngpl/entando-core-bom.git .

          ls -l

          # get the current artifact version in the entando-core-bom pom.xml file
          artifactVersionInBom=$(xmlstarlet sel -N pom="http://maven.apache.org/POM/4.0.0" -t \
            -m "/pom:project/pom:properties" \
            -v "./pom:$artifactId.version" pom.xml) || true

          echo "##### ARTIFACT VERSION $artifactVersionInBom"

          # if the current project is a dependendcy of entando-core-bom => exit OK
          [ -z "$artifactVersionInBom" ] && echo "Dependency int the entando-core-bom not found" && exit 0

          echo "UPDATING entando-core-bom pom.xml file..."

          # update the version of the current project in the entando-core-bom pom.xml file
          xmlstarlet ed --inplace -P -N pom=http://maven.apache.org/POM/4.0.0 \
              --update "/pom:project/pom:properties/pom:$artifactId.version" \
              -v "$tagValue" pom.xml

          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

          # commit
          echo "PRE ADD"
          git add pom.xml
          echo "PRE COMMIT"
          git commit -m "Bumped $artifactId to $tagValue"
          echo "PRE PUSH"
          git push
          echo "PUSHED"
