name: Publish to Entando Nexus

on:
#  push:
#    branches:
#      - "rel_v*"
#    tags:
#      - 'v*'
  release:
    types:
#      - published
#      - unpublished
      - created
#      - edited
#      - deleted
#      - prereleased
#      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Set up Entando Nexus Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ng-pipelines
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: |
          echo "### MAVEN_USERNAME $MAVEN_USERNAME"
          echo "### MAVEN_PASSWORD $MAVEN_PASSWORD"
          ls ~
          ls ~/.m2
          cat ~/.m2/settings.xml
          env
          echo "---------------------------------------------"
          mvn --batch-mode deploy -X
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
